server:
  port: 8000

spring:
  main:
    allow-bean-definition-overriding: true

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF


