server:
  port: 8010

spring:
  application:
    name: survey-service
  main:
    allow-bean-definition-overriding: true

feign:
  client:
    refresh-enabled: true
  circuitbreaker:
    enabled: true

management:
  endpoints:
    jmx:
      exposure:
        include: health,info,env,beans
    web:
      exposure:
        include: health,info,env,beans

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka
  instance:
    hostname: localhost
    preferIpAddress: true
